name: CI devops 2024

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout code
      - uses: actions/checkout@v2.5.0

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn clean verify -f ./simple-api/pom.xml

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Login to DockerHub using --password-stdin
      - name: Login to DockerHub
